import { Product } from "@/types/product";

export const featuredProducts: Product[] = [
  {
    id: 1,
    name: "Royal Moroccan Abaya",
    price: 1299,
    image: "/images/1.jpg",
    category: "Abayas",
    description: "Elegant royal abaya in Moroccan style.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gold"],
    material: "Silk",
    brand: "Royal Styles",
    inStock: true,
    images: ["/images/1.jpg", "/images/1b.jpg"],
  },
  {
    id: 2,
    name: "Premium Silk Hijab",
    price: 299,
    image: "/images/2.jpg",
    category: "Hijabs",
    description: "Soft and luxurious silk hijab for everyday wear.",
    sizes: ["One Size"],
    colors: ["White", "Beige", "Black"],
    material: "Silk",
    brand: "Elegance",
    inStock: true,
    images: ["/images/2.jpg", "/images/2b.jpg"],
  },
  {
    id: 3,
    name: "Elegant Evening Kaftan",
    price: 1599,
    image: "/images/3.jpg",
    category: "Kaftans",
    description: "A luxurious evening kaftan with intricate embroidery.",
    sizes: ["M", "L", "XL"],
    colors: ["Blue", "Gold"],
    material: "Chiffon",
    brand: "Glamour Wear",
    inStock: true,
    images: ["/images/3.jpg"],
  },
  {
    id: 4,
    name: "Casual Denim Jacket",
    price: 799,
    image: "/images/4.jpg",
    category: "Jackets",
    description: "Stylish casual denim jacket for all seasons.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Denim Blue", "Black"],
    material: "Denim",
    brand: "Urban Wear",
    inStock: true,
    images: ["/images/4.jpg"],
  },
  {
    id: 5,
    name: "Elegant Black Gown",
    price: 1899,
    image: "/images/5.jpg",
    category: "Dresses",
    description: "A beautiful black gown for evening parties.",
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    material: "Satin",
    brand: "Elegant Couture",
    inStock: true,
    images: ["/images/5.jpg"],
  },
  {
    id: 6,
    name: "Classic Leather Wallet",
    price: 499,
    image: "/images/6.jpg",
    category: "Accessories",
    description: "A classic leather wallet with multiple card holders.",
    sizes: ["One Size"],
    colors: ["Brown", "Black"],
    material: "Leather",
    brand: "LeatherCraft",
    inStock: true,
    images: ["/images/6.jpg"],
  },
  {
    id: 7,
    name: "Comfortable Cotton Kurti",
    price: 699,
    image: "/images/7.jpg",
    category: "Kurtis",
    description: "A comfortable cotton kurti for everyday wear.",
    sizes: ["S", "M", "L"],
    colors: ["Pink", "Green"],
    material: "Cotton",
    brand: "CottonFeel",
    inStock: true,
    images: ["/images/7.jpg"],
  },
  {
    id: 8,
    name: "Designer Gold Earrings",
    price: 2499,
    image: "/images/8.jpg",
    category: "Jewelry",
    description: "Elegant designer gold earrings with intricate designs.",
    sizes: ["One Size"],
    colors: ["Gold"],
    material: "Gold",
    brand: "Luxury Jewelry",
    inStock: true,
    images: ["/images/8.jpg"],
  },
  {
    id: 9,
    name: "Luxury Handbag",
    price: 3499,
    image: "/images/9.jpg",
    category: "Bags",
    description: "A luxury handbag made of premium leather.",
    sizes: ["One Size"],
    colors: ["Black", "Brown"],
    material: "Leather",
    brand: "Elegance",
    inStock: true,
    images: ["/images/9.jpg"],
  },
  {
    id: 10,
    name: "Formal Leather Shoes",
    price: 1599,
    image: "/images/10.jpg",
    category: "Shoes",
    description: "Formal leather shoes for special occasions.",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "Brown"],
    material: "Leather",
    brand: "LeatherFit",
    inStock: true,
    images: ["/images/10.jpg"],
  },
  {
    id: 11,
    name: "Vintage Aviator Sunglasses",
    price: 999,
    image: "/images/11.jpg",
    category: "Accessories",
    description: "Classic aviator sunglasses with a vintage touch.",
    sizes: ["One Size"],
    colors: ["Gold", "Silver"],
    material: "Metal",
    brand: "Retro Style",
    inStock: true,
    images: ["/images/11.jpg"],
  },
  {
    id: 12,
    name: "Classic White T-Shirt",
    price: 199,
    image: "/images/12.jpg",
    category: "Tops",
    description: "A simple and classic white t-shirt for casual wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    material: "Cotton",
    brand: "Casual Wear",
    inStock: true,
    images: ["/images/12.jpg"],
  },
  {
    id: 13,
    name: "Comfortable Sports Sneakers",
    price: 1299,
    image: "/images/13.jpg",
    category: "Shoes",
    description: "Comfortable sneakers designed for sports and active wear.",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "White", "Red"],
    material: "Mesh, Rubber",
    brand: "SportX",
    inStock: true,
    images: ["/images/13.jpg"],
  },
  {
    id: 14,
    name: "Winter Woolen Scarf",
    price: 399,
    image: "/images/14.jpg",
    category: "Accessories",
    description: "Warm woolen scarf perfect for cold weather.",
    sizes: ["One Size"],
    colors: ["Red", "Blue", "Gray"],
    material: "Wool",
    brand: "WinterWarm",
    inStock: true,
    images: ["/images/14.jpg"],
  },
  {
    id: 15,
    name: "Elegant Wedding Sherwani",
    price: 3999,
    image: "/images/15.jpg",
    category: "Menswear",
    description: "A luxurious wedding sherwani with intricate embroidery.",
    sizes: ["M", "L", "XL"],
    colors: ["Ivory", "Gold"],
    material: "Silk",
    brand: "Royal Designs",
    inStock: true,
    images: ["/images/15.jpg"],
  },
  {
    id: 16,
    name: "Silk Printed Saree",
    price: 1999,
    image: "/images/16.jpg",
    category: "Sarees",
    description: "A beautifully printed silk saree for festive occasions.",
    sizes: ["One Size"],
    colors: ["Red", "Green"],
    material: "Silk",
    brand: "Traditional Wear",
    inStock: true,
    images: ["/images/16.jpg"],
  },
  {
    id: 17,
    name: "Kids’ Cartoon T-Shirt",
    price: 299,
    image: "/images/17.jpg",
    category: "Kids",
    description: "Fun cartoon-themed t-shirt for kids.",
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Pink"],
    material: "Cotton",
    brand: "KiddoStyle",
    inStock: true,
    images: ["/images/17.jpg"],
  },
  {
    id: 18,
    name: "Luxury Bed Linens Set",
    price: 2999,
    image: "/images/18.jpg",
    category: "Home",
    description: "A luxurious set of bed linens for a comfortable sleep.",
    sizes: ["Queen", "King"],
    colors: ["White", "Beige"],
    material: "Cotton",
    brand: "Home Comfort",
    inStock: true,
    images: ["/images/18.jpg"],
  },
  {
    id: 19,
    name: "Elegant Watch",
    price: 1999,
    image: "/images/19.jpg",
    category: "Accessories",
    description: "An elegant watch with a classic design.",
    sizes: ["One Size"],
    colors: ["Black", "Silver"],
    material: "Stainless Steel",
    brand: "Timeless",
    inStock: true,
    images: ["/images/19.jpg"],
  },
  {
    id: 20,
    name: "Waterproof Hiking Backpack",
    price: 1299,
    image: "/images/20.jpg",
    category: "Bags",
    description: "A waterproof hiking backpack for outdoor adventures.",
    sizes: ["One Size"],
    colors: ["Green", "Black"],
    material: "Nylon",
    brand: "Adventure Gear",
    inStock: true,
    images: ["/images/20.jpg"],
  },
];
